export const CATEGORY_CALLBACK_MAP: Record<string, string> = {
  cat_alcohol: 'Alcohol',
  cat_clothing: 'Clothing',
  cat_education: 'Education',
  cat_electric: 'Electric',
  cat_electronics: 'Electronics',
  cat_entertainment: 'Entertainment',
  cat_food: 'Food',
  cat_gas: 'Gas/Fuel',
  cat_gifts: 'Gifts',
  cat_groceries: 'Groceries',
  cat_gym: 'Gym',
  cat_health: 'Health',
  cat_insurance: 'Insurance',
  cat_internet: 'Internet',
  cat_maintenance: 'Maintenance',
  cat_medical: 'Medical',
  cat_other: 'Other',
  cat_parking: 'Parking',
  cat_personal_care: 'Personal Care',
  cat_phone: 'Phone',
  cat_public_transit: 'Public Transit',
  cat_rent: 'Rent',
  cat_rideshare: 'Rideshare',
  cat_shopping: 'Shopping',
  cat_taxes: 'Taxes',
  cat_travel: 'Travel',
  cat_water: 'Water',
};

export const INCOME_TYPE_CALLBACK_MAP: Record<string, string> = {
  inc_salary: 'Salary',
  inc_freelance: 'Freelance',
  inc_side_income: 'Side Income',
  inc_refund: 'Refund',
  inc_gift: 'Gift',
  inc_dividends: 'Dividends',
};
